In [50]:
import pandas as pd
import numpy as np

In [51]:
train = pd.read_csv("../Output/OPT_Training_Set_grouped_binary.csv")
test = pd.read_csv("../Output/OPT_Testing_Set_grouped_binary.csv")

In [52]:
train = train.drop("Unnamed: 0", axis=1)
test = test.drop("Unnamed: 0", axis=1)

In [53]:
treatments = ["med_change_1_NoMed","med_change_1_Steady", "med_change_1_Up", "med_change_2_Mixed",
                    "med_change_2_NoMed", "med_change_2_Steady", "med_change_2_Up",
                    "med_change_3_NoMed", "med_change_3_Steady", "med_change_3_Up", 
                    "med_change_4_NoMed", "med_change_4_Steady", "med_change_4_Up",
                    "med_change_5_NoMed", "med_change_5_Steady", "med_change_5_Up",
                    "med_change_6_NoMed", "med_change_6_Steady", "med_change_6_Up",
                    "med_change_other_Yes"]

In [54]:
treatments_train = train[treatments]
treatments_test = test[treatments]
treatments_train

,med_change_1_NoMed,med_change_1_Steady,med_change_1_Up,med_change_2_Mixed,med_change_2_NoMed,med_change_2_Steady,med_change_2_Up,med_change_3_NoMed,med_change_3_Steady,med_change_3_Up,med_change_4_NoMed,med_change_4_Steady,med_change_4_Up,med_change_5_NoMed,med_change_5_Steady,med_change_5_Up,med_change_6_NoMed,med_change_6_Steady,med_change_6_Up,med_change_other_Yes
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49759,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
49760,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
49761,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
49762,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
49763,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [55]:
unique_counts = treatments_train.groupby(list(treatments_train.columns)).size().reset_index(name='Counts')
unique_counts_sorted = unique_counts.sort_values(by=["Counts"], ascending=False)
unique_counts_sorted

,med_change_1_NoMed,med_change_1_Steady,med_change_1_Up,med_change_2_Mixed,med_change_2_NoMed,med_change_2_Steady,med_change_2_Up,med_change_3_NoMed,med_change_3_Steady,med_change_3_Up,...,med_change_4_Steady,med_change_4_Up,med_change_5_NoMed,med_change_5_Steady,med_change_5_Up,med_change_6_NoMed,med_change_6_Steady,med_change_6_Up,med_change_other_Yes,Counts
348,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,11312
346,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,8005
287,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,3861
344,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3740
345,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
45,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1
220,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1
221,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1

### Extract rows with top 3 treatments only

In [56]:
unique_counts_sorted_top3 = unique_counts_sorted.head(3)
sum(unique_counts_sorted_top3['Counts'])

23178

In [57]:
Testing_Filtered_top3 = pd.merge(test, unique_counts_sorted_top3.iloc[:, 0:20], how="inner", on=list(treatments_train.columns))
Testing_Filtered_top3

,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,med_count_1,...,diag1_category_5,diag1_category_6,diag1_category_7,diag1_category_8,diag1_category_9,diag1_category_Unknown,max_glu_serum_cleaned_>300,max_glu_serum_cleaned_Norm,max_glu_serum_cleaned_Not Taken,readmitted
0,5,1,41,0,1,0,0,0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
1,75,2,47,0,12,0,0,0,8,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
2,85,11,42,2,19,0,0,0,8,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
3,55,4,40,1,14,0,0,0,9,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
4,75,7,75,2,22,0,0,0,7,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23014,55,2,28,0,13,0,0,0,9,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
23015,85,2,54,1,10,0,0,3,9,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
23016,75,2,48,0,18,0,0,0,9,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
23017,75,5,21,1,16,0,0,1,9,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0
23018,85,5,33,3,18,0,0,1,9,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0

In [58]:
Training_Filtered_top3 = pd.merge(train, unique_counts_sorted_top3.iloc[:, 0:20], how="inner", on=list(treatments_train.columns))
Training_Filtered_top3

,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,med_count_1,...,diag1_category_5,diag1_category_6,diag1_category_7,diag1_category_8,diag1_category_9,diag1_category_Unknown,max_glu_serum_cleaned_>300,max_glu_serum_cleaned_Norm,max_glu_serum_cleaned_Not Taken,readmitted
0,25,2,11,5,13,2,0,1,6,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
1,65,1,58,1,12,0,0,0,6,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
2,65,1,31,2,8,0,0,0,5,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,75,4,46,5,12,0,0,0,7,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1
4,45,2,52,0,12,0,0,0,7,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23173,75,5,63,1,23,0,0,0,15,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
23174,95,6,60,0,20,0,1,0,9,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
23175,75,3,57,4,11,0,0,1,9,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
23176,95,4,21,1,8,0,0,1,9,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
23177,75,6,13,3,3,0,0,0,9,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0

In [59]:
#Save CSVs
Training_Filtered_top3.to_csv("../Output/Training_Filtered_top3_long.csv")
Testing_Filtered_top3.to_csv("../Output/Testing_Filtered_top3_long.csv")

### Extract rows with top 10 treatments only

In [60]:
## Extract top 10 treatments
unique_counts_sorted_top10 = unique_counts_sorted.head(10)
sum(unique_counts_sorted_top10['Counts'])

38251

In [61]:
Testing_Filtered_top10 = pd.merge(test, unique_counts_sorted_top10.iloc[:, 0:20], how="inner", on=list(treatments_train.columns))
Training_Filtered_top10 = pd.merge(train, unique_counts_sorted_top10.iloc[:, 0:20], how="inner", on=list(treatments_train.columns))

In [62]:
Training_Filtered_top10.to_csv("../Output/Training_Filtered_top10_long.csv")
Testing_Filtered_top10.to_csv("../Output/Testing_Filtered_top10_long.csv")